# Custom ROS packages:
core_pkg:
  ubuntu:
    xenial:
      apt:
        packages: [ros-kinetic-core-pkg]

air_core_pkg:
  ubuntu:
    xenial:
      apt:
        packages: [ros-kinetic-air-core-pkg]
